### ISSUE TITLE
install failed in deb 11 224: [: false: unexpected operator

### ISSUE THREAD

**Issue by nicholasglazer** [surrealdb/install.surrealdb.com#11]
if anyone else is getting this error, mine was in fresh deb 11 server, 
just replace == with = in line or add double brackets and keep == in line 224
https://github.com/surrealdb/install.surrealdb.com/blob/fe4756cb1ac07717497b9e3d37adfd840ccca1a1/index.sh#L224C5-L224C44

![1710171802_2024-03-11-21_13](https://github.com/surrealdb/install.surrealdb.com/assets/7410355/b822c9d8-dcb9-4e53-af31-4c306210fafe)

I've opened a PR 
https://github.com/surrealdb/install.surrealdb.com/pull/12

**Comment by nealtaylor98** [comment]
for anyone else that stumbles across this - if you'd like to install with a single command, the following worked for me. (Using WSL and Ubuntu)
`curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sed '244s/==/=/' | sh`
You might have to replace the line number with the number you see in the error `sh: 224: [:...`

**Comment by tobiemh** [comment]
Fixed by #12
