### ISSUE TITLE
Bug: Linux Installation Failure 

### ISSUE THREAD

**Issue by felipetesc** [surrealdb/install.surrealdb.com#3]
### Describe the bug

Surreal database installation fails on Arch Linux - Garuda, when I execute the default command provided from https://surrealdb.com/install.

PS: If I run the command "curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh -s -- --nightly" the database installation succeeds.

### Steps to reproduce

1 - Open the terminal
2 - TYpe the command : curl -sSf https://install.surrealdb.com | sh (at https://surrealdb.com/install)
![print](https://user-images.githubusercontent.com/2336812/228314085-387c75a1-8555-4bc8-93f3-58eda21e80ac.png)

Result: the command outputs "main: line 58: $1: unbound variable".

### Expected behaviour

To install the database.

### SurrealDB version

surreal for archlinux on x64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobiemh** [comment]
Thanks for spotting this @felipetesc. This should be fixed now!
